# Generated by Django 3.1.7 on 2021-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.IntegerField()),
                ('cuname', models.CharField(max_length=70)),
                ('cumail', models.EmailField(max_length=50)),
                ('cupass', models.CharField(max_length=50)),
            ],
        ),
    ]
