# Generated by Django 3.1.7 on 2021-04-06 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdb',
            name='pubdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
