# Generated by Django 3.1.7 on 2021-04-08 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcom', '0002_customerdb_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdb',
            name='Discription',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
