# Generated by Django 3.1.7 on 2021-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcom', '0003_customerdb_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='cuid',
            field=models.IntegerField(null=True),
        ),
    ]
