# Generated by Django 3.1.7 on 2021-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcom', '0004_auto_20210413_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='cupass',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
